name: Deploy AI Tools Directory to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'data/**'
      - 'package.json'
      - 'next.config.js'
      - 'next-sitemap.config.js'
      - 'tailwind.config.js'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
        
    - name: Validate data integrity
      run: npm run validate
        
    - name: Build Next.js application
      run: npm run build
      
    - name: Export static site
      run: npm run export

    - name: Add .nojekyll file
      run: touch out/.nojekyll

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Output deployment URL
        run: |
          echo "🚀 Site deployed with sitemap.xml and robots.txt"
